-- ==============================================================================
-- CJVELORA — Supabase Products Seed Script (21 Products)
-- ==============================================================================
-- Seeds all 21 existing handcrafted creations into the Supabase 'products' table.
-- Accurately preserves names, slugs, descriptions, prices, compare_at_prices,
-- materials, dimensions, care instructions, image references, best-seller status,
-- ratings, and links each product to its category via (SELECT id FROM categories).
-- ==============================================================================

INSERT INTO public.products (
  category_id,
  name,
  slug,
  price,
  compare_at_price,
  description,
  long_description,
  materials,
  dimensions,
  care_instructions,
  image_url,
  badge,
  is_best_seller,
  is_made_to_order,
  lead_time,
  rating,
  review_count,
  in_stock,
  colors
)
VALUES
  -- 1. CROCHET BAGS
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-bags' LIMIT 1),
    'Artisan Open-Weave Tote Bag',
    'artisan-open-weave-tote-bag',
    3499,
    3999,
    'Handmade luxury open-weave cotton tote bag with reinforced handles and organic cotton lining.',
    'Each Artisan Open-Weave Tote is crafted over 14 hours by our senior artisans. Made with 100% GOTS-certified organic cotton, it balances airy bohemian flair with exceptional weight-bearing structural durability.',
    '100% Organic OEKO-TEX Cotton Yarn',
    '38cm x 42cm (Drop handle: 26cm)',
    'Gentle hand wash in cold water with mild organic wool detergent. Lay flat to dry.',
    '/images/products/tote-bag.jpg',
    'Bestseller',
    true,
    false,
    NULL,
    4.95,
    52,
    true,
    ARRAY['Oatmeal Ivory', 'Sage Olive', 'Midnight Navy']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-bags' LIMIT 1),
    'Bohemian Granny Square Carryall',
    'bohemian-granny-square-carryall',
    3899,
    4299,
    'Vintage-inspired floral motif granny square shoulder bag with natural wooden ring handle accents.',
    'A modern tribute to traditional artisan crochet. Constructed by seamlessly joining 18 individual floral motif granny squares, each edged in botanical olive and champagne threads.',
    'Natural Combed Cotton & Solid Beechwood Rings',
    '34cm x 36cm x 10cm',
    'Spot clean only with damp cloth.',
    'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=900&auto=format&fit=crop',
    'Handmade Special',
    false,
    true,
    '5-7 business days',
    4.88,
    29,
    true,
    ARRAY['Vintage Terracotta', 'Sand & Cream']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-bags' LIMIT 1),
    'Petite Crossbody Shell Pouch',
    'petite-crossbody-shell-pouch',
    2199,
    2499,
    'Delicate scallop-stitch compact crossbody pouch with magnetic brass snap closure and braided strap.',
    'The perfect companion for light travels, festivals, and evenings out. Finished with antique brass hardware and reinforced corded shoulder strap.',
    'Mercerized Egyptian Cotton Thread',
    '20cm x 18cm (Strap length: 115cm)',
    'Hand wash cold and dry flat.',
    'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=900&auto=format&fit=crop',
    'New',
    false,
    false,
    NULL,
    4.80,
    16,
    true,
    ARRAY['Opal White', 'Dusty Rose', 'Forest Olive']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-bags' LIMIT 1),
    'Coastal Net Market Bag',
    'coastal-net-market-bag',
    1899,
    NULL,
    'Expandable French mesh-style crochet market net bag that stretches naturally to hold farmers market produce.',
    NULL,
    'Unbleached Raw Organic Cotton',
    '40cm length (expands up to 60cm)',
    'Machine washable on gentle cycle.',
    'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?q=80&w=900&auto=format&fit=crop',
    NULL,
    false,
    false,
    NULL,
    4.75,
    22,
    true,
    ARRAY['Raw Ecru', 'Sage Green']
  ),

  -- 2. CROCHET TOYS
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-toys' LIMIT 1),
    'Heirloom Amigurumi Teddy Bear',
    'heirloom-amigurumi-teddy-bear',
    1899,
    2199,
    'Hypoallergenic organic cotton amigurumi companion stuffed with anti-dust mite natural kapok fiber.',
    'Created with child-safe safety-locked embroidered eyes and hypoallergenic natural cotton threads. An heirloom keepsake crafted to be cherished across generations.',
    '100% Organic Bamboo Cotton & Kapok Fiber',
    '28cm standing height',
    'Surface wipe with damp cloth and gentle soap.',
    '/images/products/teddy-bear.jpg',
    'Heirloom Gift',
    true,
    false,
    NULL,
    4.98,
    68,
    true,
    ARRAY['Warm Honey', 'Soft Oat', 'Pastel Blossom']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-toys' LIMIT 1),
    'Woodland Bunny in Knitted Romper',
    'woodland-bunny-in-knitted-romper',
    2099,
    NULL,
    'Adorable long-eared plush bunny complete with a removable tiny knitted overalls set.',
    NULL,
    'Organic Milk Cotton Yarn',
    '32cm ear to toe',
    'Hand wash gently with baby soap.',
    'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=900&auto=format&fit=crop',
    'Customer Favorite',
    false,
    false,
    NULL,
    4.92,
    44,
    true,
    ARRAY['Oatmeal / Sage Overalls', 'Cream / Blush Overalls']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-toys' LIMIT 1),
    'Artisan Baby Rattle & Teether',
    'artisan-baby-rattle-teether',
    999,
    NULL,
    'Soothing natural beechwood teething ring wrapped with soft organic crochet deer head and gentle rattle chime.',
    NULL,
    'Unfinished Natural Beechwood & Organic Cotton',
    '14cm x 8cm',
    'Wipe clean with food-grade damp cloth.',
    'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=900&auto=format&fit=crop',
    NULL,
    false,
    false,
    NULL,
    4.90,
    37,
    true,
    NULL
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-toys' LIMIT 1),
    'Sleepy Fox Nursery Companion',
    'sleepy-fox-nursery-companion',
    1799,
    NULL,
    'Charming sleeping woodland fox with embroidered closed eyes and soft fluffy tail.',
    NULL,
    'Hypoallergenic Cotton Yarn',
    '22cm length',
    'Spot clean only.',
    'https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=900&auto=format&fit=crop',
    NULL,
    false,
    false,
    NULL,
    4.85,
    19,
    true,
    NULL
  ),

  -- 3. CROCHET KITCHENS
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-kitchens' LIMIT 1),
    'Waffle Dishcloth & Trivet Set',
    'waffle-dishcloth-trivet-set',
    1499,
    1799,
    'Hand-knitted waffle dishcloths, thick cotton trivet pads, and heat-resistant artisan pot holders in natural tones.',
    'Transform your kitchen counters with tactile luxury. This 4-piece set features double-thick textured honeycomb stitches designed for optimal water absorbency and thermal insulation from hot cookware.',
    'Natural Unbleached Egyptian Cotton',
    'Trivet: 22cm diameter | Dishcloths: 25cm x 25cm',
    'Machine washable on delicate cycle in laundry bag. Tumble dry low.',
    '/images/products/dishcloth-trivet.jpg',
    'Eco-Friendly',
    true,
    false,
    NULL,
    4.85,
    38,
    true,
    ARRAY['Warm Sand', 'Olive Mist', 'Terracotta']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-kitchens' LIMIT 1),
    'Artisan Hexagon Coaster Set (Pack of 6)',
    'artisan-hexagon-coaster-set',
    899,
    NULL,
    'Thick braided double-stitch absorbent cotton coasters with scalloped borders in presentation gift band.',
    NULL,
    '100% Heavy Gauge Organic Cotton',
    '11cm point to point',
    'Machine washable cold.',
    'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=900&auto=format&fit=crop',
    'Best Value',
    false,
    false,
    NULL,
    4.90,
    51,
    true,
    ARRAY['Ivory & Taupe Mix', 'Forest Green Blend']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-kitchens' LIMIT 1),
    'Cast Iron Handle Pot Grips (Set of 2)',
    'cast-iron-handle-pot-grips',
    699,
    NULL,
    'Heavy thermal double-layered heat protection sleeves custom looped for skillet handles.',
    NULL,
    'Pure Thick Unbleached Cotton',
    '15cm x 6cm',
    'Washable cold.',
    'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=900&auto=format&fit=crop',
    NULL,
    false,
    false,
    NULL,
    4.78,
    20,
    true,
    NULL
  ),

  -- 4. CROCHET GIFTS
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-gifts' LIMIT 1),
    'Everlasting Crochet Floral Bouquet',
    'everlasting-crochet-floral-bouquet',
    2799,
    3299,
    'Handcrafted forever bouquet featuring crochet tulips, daisies, and lavender sprigs in signature linen wrapping.',
    'An immortal symbol of affection and warmth. Each petal and leaf is hand-formed with fine mercerized cotton and supported by flexible floral wire stems.',
    'Mercerized Cotton Thread & Floral Stems',
    '35cm stem height | 7-stem bouquet',
    'Dust lightly with soft brush.',
    '/images/products/floral-bouquet.jpg',
    'Popular Gift',
    true,
    true,
    '3-5 business days',
    4.96,
    73,
    true,
    ARRAY['Spring Pastel', 'Sunlit Sunflower', 'Wildflower Romance']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-gifts' LIMIT 1),
    'Crochet Evil Eye Talisman Keychain',
    'crochet-evil-eye-talisman-keychain',
    799,
    999,
    'Protective Turkish blue and gold evil eye talisman with brass clasp and soft cotton tassel.',
    NULL,
    'Silky Mercerized Yarn & Solid Brass Hardware',
    '12cm total length',
    'Wipe clean.',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=900&auto=format&fit=crop',
    'Keepsake',
    false,
    false,
    NULL,
    4.90,
    88,
    true,
    NULL
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-gifts' LIMIT 1),
    'Bespoke Monogrammed Bookmark',
    'bespoke-monogrammed-bookmark',
    499,
    NULL,
    'Intricate lace-stitch bookmark finished with hand-embroidered initial and tassel fringe.',
    NULL,
    'Fine Egyptian Lace Thread',
    '22cm x 4cm',
    'Press with warm iron under towel.',
    'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=900&auto=format&fit=crop',
    NULL,
    false,
    true,
    '2-3 business days',
    4.88,
    31,
    true,
    NULL
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'crochet-gifts' LIMIT 1),
    'Sunflower Car Hanging Charm',
    'sunflower-car-hanging-charm',
    899,
    NULL,
    'Bright cheerful handmade crochet sunflower charm for car rearview mirrors or bag charms.',
    NULL,
    'Vibrant Organic Cotton Thread',
    '8cm sunflower diameter',
    'Spot clean.',
    'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?q=80&w=900&auto=format&fit=crop',
    NULL,
    false,
    false,
    NULL,
    4.86,
    42,
    true,
    NULL
  ),

  -- 5. DREAM CATCHERS
  (
    (SELECT id FROM public.categories WHERE slug = 'dream-catchers' LIMIT 1),
    'Sacred Mandala Dream Catcher',
    'sacred-mandala-dream-catcher',
    2499,
    2899,
    'Spiritual yarn web dreamcatcher embellished with raw wooden beads and artisanal flowing lace fringe.',
    'Woven with intentional geometry inspired by sacred mandalas. Features hand-carved sustainable neem wood beads and cascading textured cotton fringe.',
    'Raw Cotton Yarn, Brass Ring, Natural Wood Beads',
    '25cm ring diameter | 70cm total hanging length',
    'Gently comb fringe with wide-tooth comb occasionally.',
    '/images/products/dream-catcher.jpg',
    'Handmade Soul',
    true,
    false,
    NULL,
    5.00,
    49,
    true,
    ARRAY['Boho Natural', 'Sun-Kissed Ochre', 'Deep Forest']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'dream-catchers' LIMIT 1),
    'Moonlight Trio Hanging Tapestry',
    'moonlight-trio-hanging-tapestry',
    3499,
    NULL,
    'Triple connected brass hoops woven with intricate starburst crochet webs and dip-dyed ombre fringe.',
    NULL,
    'Natural Cotton & Dip-Dyed Botanical Inks',
    '45cm width x 85cm length',
    'Hang flat and gently smooth fringe.',
    'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=900&auto=format&fit=crop',
    'Statement Piece',
    false,
    true,
    '6-8 business days',
    4.95,
    23,
    true,
    ARRAY['Earthy Sand Ombre', 'Indigo Midnight']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'dream-catchers' LIMIT 1),
    'Miniature Car Dream Catcher',
    'miniature-car-dream-catcher',
    799,
    NULL,
    'Delicate 7cm hoop dreamcatcher crafted with tiny wooden beads and soft feather-stitch yarn pendants.',
    NULL,
    'Cotton Thread & Wood Beads',
    '7cm diameter x 20cm length',
    'Dust lightly.',
    'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=900&auto=format&fit=crop',
    NULL,
    false,
    false,
    NULL,
    4.82,
    30,
    true,
    NULL
  ),

  -- 6. TABLE MATS
  (
    (SELECT id FROM public.categories WHERE slug = 'table-mats' LIMIT 1),
    'Medallion Floral Dining Placemat Set (Set of 4)',
    'medallion-floral-dining-placemat-set',
    2299,
    2699,
    'Lacy floral crochet dining placemats woven with fine thread and heat-resistant textured centers.',
    'Brings authentic French bistro elegance to dining tables. Designed to elevate dinner parties and daily morning coffee rituals alike.',
    '100% Fine Combed Cotton Thread',
    '35cm diameter',
    'Hand wash cold or machine wash delicate. Lay flat to dry.',
    '/images/products/placemat-set.jpg',
    'Artisan Dining',
    true,
    false,
    NULL,
    4.93,
    36,
    true,
    ARRAY['Pristine Ivory', 'Vintage Linen', 'Olive Garden']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'table-mats' LIMIT 1),
    'Heritage Lattice Table Runner',
    'heritage-lattice-table-runner',
    2899,
    3299,
    '6-foot long centerpiece table runner featuring open diamond lattice work and scalloped tassel ends.',
    NULL,
    'Unbleached Organic Cotton',
    '18cm x 35cm',
    'Gentle flat hand wash.',
    'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=900&auto=format&fit=crop',
    'Heritage',
    false,
    true,
    '5-7 business days',
    4.90,
    21,
    true,
    ARRAY['Warm Ecru', 'Natural Flax']
  ),
  (
    (SELECT id FROM public.categories WHERE slug = 'table-mats' LIMIT 1),
    'Scalloped Teacup Coaster & Mug Rug (Set of 4)',
    'scalloped-teacup-coaster-mug-rug',
    799,
    NULL,
    'Thick soft textured mug rugs with miniature fringed edges for afternoon tea cups and coffee mugs.',
    NULL,
    'Organic Soft Cotton',
    '15cm x 12cm',
    'Machine wash delicate.',
    'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?q=80&w=900&auto=format&fit=crop',
    NULL,
    false,
    false,
    NULL,
    4.87,
    28,
    true,
    NULL
  )
ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  compare_at_price = EXCLUDED.compare_at_price,
  description = EXCLUDED.description,
  long_description = EXCLUDED.long_description,
  materials = EXCLUDED.materials,
  dimensions = EXCLUDED.dimensions,
  care_instructions = EXCLUDED.care_instructions,
  image_url = EXCLUDED.image_url,
  badge = EXCLUDED.badge,
  is_best_seller = EXCLUDED.is_best_seller,
  is_made_to_order = EXCLUDED.is_made_to_order,
  lead_time = EXCLUDED.lead_time,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  in_stock = EXCLUDED.in_stock,
  colors = EXCLUDED.colors;

-- Ensure RLS allows public SELECT on products:
ALTER TABLE IF EXISTS public.products ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Allow public read access to products'
  ) THEN
    CREATE POLICY "Allow public read access to products"
      ON public.products
      FOR SELECT
      TO anon, authenticated
      USING (true);
  END IF;
END $$;
